name: github
version: 3.0.0
author: Kenneth Endfinger <kaendfinger@gmail.com>
description: GitHub API Client Library
homepage: https://github.com/DirectMyFile/github.dart
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  html: '>=0.12.0 <0.14.0'
  http: '^0.11.3'
  quiver: '>=0.20.0 <0.25.0'
  xml: '^2.0.0'
  markdown: '^0.11.1'
dev_dependencies:
  browser: '^0.10.0+2'
  test: '^0.12.0'
  mockito: '^1.0.1'
